### ISSUE TITLE
So, how do I start my own self-hosted pod?

### ISSUE THREAD

**Issue by lwojcik** [jointwt/twtxt#144]
I'm getting close to finishing stuff I've had on my plate for a while and I'm getting ready to get my own pod. However, I don't want to use [twt.social](https://twt.social/) for that. I believe opting for a harder route will enable me to generate more reusable knowledge to share with wider community as well as embrace the aspect of _almost fully owning_ the infrastructure I use on everyday basis. My general plan is to set up a pod for myself and observe how it works. Once I get comfortable with managing it for myself, I'll seriously consider switching it to a public instance free to use for other people (I even bought a domain for that but shhhh) so that I can claim it to be the first Europe-based Twt instance [with all its glory and all its horror](https://www.youtube.com/watch?v=VSGmPpidDvo&t=200).

My initial infrastructure as of now consists of a budget VPS (1 vCore, 2 GB RAM, 20 GB SSD SATA, 100 Mbps) running Debian stable. ~90% of resources are free to use for most of the time.

Looking at the twtxt, I can see two ways of getting my own Twt pod up and running:

* git cloning source code from GitHub, satisfying any dependencies needed, building the project according to instructions and letting it face the public via Nginx as reverse proxy or any other similar toolset + writing and sharing an Ansible role to make the process idempotent,

* fetching latest binary from GitHub releases and doing whatever needed to get it running.

First option seems to be more time consuming, plus it implies I know stuff about Go development. The silver lining is that once I document all steps needed to reproduce the project / write an Ansible role, it won't matter that much. To open my pod to general public I need to understand what exactly I have to do to get reproducible builds whenever anything of importance happens in the project or [my infrastructure goes Canon](https://www.techradar.com/news/canon-says-its-cloud-service-cant-restore-users-lost-videos-or-full-size-images). I don't mind running updates many times a day should critical bugs occur. However, going this route also means I have to dig deep into project internals and get answers to very specific questions, such as how the project stores user configuration data, how to handle traffic, how to utilize external tools to offload traffic. And most importantly, this means I'll ask a lot of annoying questions about starting and maintaing the project.

Second option seems to be easier and much quicker to kickstart but running a pre-built binary means I have to wait for bugs to be fixed until the next release. It probably wouldn't be that much of a pain if CI/CD workflow would have been set up to generate daily builds. That way I could very easily automate fetching and installing latest available release once a day. However, I'd also have to agree to run a binary I know very little about and assume it does magic on my machines.

First option is much more exciting but I need instructions how to prepare my infrastructure and where exactly I should start to get things going. I'm fairly capable of making Linux host what I want and I'll probably manage just fine if I'm given very general instructions to get things started (e.g. 'install X and set it up to do Y, search on Google to do that'). I have zero experience with containers / Docker / anything that adds abstraction layer between me and my Linux processes.

Second option isn't that cool, but it's less likely to decrease my sleep quality. :)

So, my general question is: how do I start?

Or in more detail: what should I read / do / install on my end to make this as painless as possible?

**Comment by prologic** [comment]
Okay... So couple of things first off.

- Yes we haven't documented this very _clearly_ (yet), there's a bit in the [README](/README.md) but we need more details docs over at [docs.twtxt.net](https://docs.twtxt.net) (_where we will continue to host Developer/Maintainer docs_).
- Both options _will_ work just fine for you! Since you don't want to go down the Docker/Container route, that's fine 😀

----

So let's use this issue as an opportunity to help document this process then! Option #1 that it, Option #2 will mostly be the same just without the "build steps". I've had to go through this a little bit with a free lancer doing some UI/UX work on the project on an Ubuntu machine for local development, so let's see how this goes!

General Steps (_from source_):

Prerequistists:

- Install [Git](https://git-scm.com/) (_optional if you just want to use the [Release Tarballs](https://github.com/jointwt/twtxt/releases) or [Latest Snapshot](https://github.com/jointwt/twtxt/archive/master.zip)_)
- Install [Go](https://golang.org)
  - Ensure you have `$GOPATH/bin` in your `$PATH` See [here](https://golang.org/doc/gopath_code.html)
- Ensure you have `make` on your system.

General steps:

- Grab the source code:

Either via `git clone`, `git pull`:

```#!console
git clone https://github.com/jointwt/twtxt.git
```

Or for an existing clone:

```#!console
cd twtxt
git pull
```

- Install any required dependencies (_tools we use to build assets and embed templates_)

```#!sh
cd twtxt
make deps
```

__NOTE:__ Bt sure `$GOPATH/bin` is in your `$PATH`.

- Build and Install it

```#!console
cd twtxt
make install
```

- Run the binary (_the defaults will work out-of-the-box_)

```#!console
cd /path/to/pod
twtd
```

Configuration:

To configure your pod, see `twtd --help`, all options can be provided via CLI flags orEnvironmentt with matching names with `-` replaced with `_` and uppercased long names.

Ingress / Reverse Proxy:

Ideally put this behind a reverse proxy like NGINX, Lighttpd or HaProxy.
(_Google for how to do this, we should not have to cover this here!_)

Any questions, keep ask'n we'll cover them in time!

**Comment by prologic** [comment]
Also we _do_ plan to automate nightly pre-built binary builds for convenience (_I know not everyone will want that and prefer to build from source_), but we will provide a self-updating binary (_can be disabled_) and daily buidls.

**Comment by prologic** [comment]
> Yes we haven't documented this very clearly (yet), there's a bit in the README but we need more details docs over at docs.twtxt.net (where we will continue to host Developer/Maintainer docs).

Sorry this is wrong. We _will_ document "How to run your own pod" in various ways over at [jointwt.org](https://jointwt.org) (cc @aaadonai). The aforementioned [dev.twtxt.net](https://dev.twtxt.net) will be more geared towards Developers with Specs, Architecture, Tech Stack, How to contribute, How to setup your dev environment, Developing Apps/Bots/Feeds, etc.

**Comment by lwojcik** [comment]
> Since you don't want to go down the Docker/Container route, that's fine grinning

Just to clarify: it's not that I have anything against Docker/containers, I just don't want to dig into them _right now_. I'll eventually move all my stuff to containers and this will definitely affect the way I run my twt instance, but at that point I'll know better what I'm doing. :)

> Ideally put this behind a reverse proxy like NGINX, Lighttpd or HaProxy.
(Google for how to do this, we should not have to cover this here!)

Fortunately I know how to do this as I use it all the time for my Node.js apps. :+1: 

Thanks for the instructions, they look clear and simple. I'll start playing with this soon.

**Comment by prologic** [comment]
> Just to clarify: it's not that I have anything against Docker/containers, I just don't want to dig into them right now. I'll eventually move all my stuff to containers and this will definitely affect the way I run my twt instance, but at that point I'll know better what I'm doing. :)

No worries! Hopefully soon you'll start to see a new repo for the infra behind Twt.social -- Briefly it is made up of:

- 5x Node Docker Swarm Cluster
- Prometheus, Grafana and AlertManager for monitoring
- Traefik ingress
- Deployments of the [twtxt.yml](https://github.com/jointwt/twtxt/blob/master/twtxt.yml) Stackfile using `docker stack deploy ...`

**Comment by prologic** [comment]
> Thanks for the instructions, they look clear and simple. I'll start playing with this soon.

Welcome! LMK if you run into any issues!

**Comment by prologic** [comment]
How are you going with this? Do you need any help? Anything I missed?

**Comment by lwojcik** [comment]
Waiting for its turn until I fix my other project, will get back to you when I have updates.

**Comment by prologic** [comment]
Came across a new Pod that [@wtux](https://twt.u53.us/user/etux) spun up over at https://twt.u53.us/ 😎

**Comment by lwojcik** [comment]
I'll be getting mine ready very soon as I have a little more spare cycles these days.

Unlike @wtux though, I'm still opting for a hard manual route of setting things manually and writing relevant Ansible roles. Docker is a part of a bigger revolution in my server stack and I want to upgrade all the things in one go.

**Comment by prologic** [comment]
Sorry I typo'd, it was `@etux` :)
