### ISSUE TITLE
Threaded / grouped replies and reactions (likes)

### ISSUE THREAD

**Issue by joshkitt** [jointwt/twtxt#169]
**Describe the solution you'd like**
I would like replies to a post to be grouped with the original post and shown under/indented so you can see what the reply belongs to. Replies currently look like a new post and it is out of context. As part of a reply, it would be nice to be able to have standard "reactions" to a post, such as a "like", "thumbs up", etc. Thank you.

**Comment by prologic** [comment]
Hello @joshkitt 👋 

We already have support for "grouping" replies together. We call them "Conversations" Next to each Twt you will see a "Conversation" button that will bring you to a view that shows _that_ conversation. This works in a similar way to Twt Blog comments.

Regarding Likes, Reactions, etc. This will require a **much larger** discussion, as I am not very fond of adding this capability at all as I feel that:

- it devalues the discussion and doesn't provide meaningful input to the conversation or discourse
- it is tempting then to use this "statistical" data for othernefariouss means (_what do you think T***, F*** do with this?_)

Thank you for your feedback! 🤗

**Comment by joshkitt** [comment]
Thank you, I appreciate your reply. I can understand the hesitancy to add reactions to posts. I do feel like it adds a level of engagement for the users to keep them engaged an interested in how others are also feeling about the post. It also allows them to show appreciation for the author and their post without needing to reply just to show appreciation (and potentially add noise to the conversation). Is it possible to offer this as an optional feature or plugin?

**Comment by prologic** [comment]
You are not the only one to argue this point, my old man in fact also said very similar things. I'm open to ideas that don't compromise on moral principles and I can understand that making it "convenient" to add a "👍" as a Reply would potentially _cause unwanted noise?". What's the middle ground here? 🤔 (cc @aaadonai @lwojcik @dooven )

**Comment by prologic** [comment]
Feel free to further discuss it [here](v) too (_dog-fooding_).

**Comment by prologic** [comment]
I just _realised_ there is a "middle ground" here _I think_:

We could store such data in the Global feed Cache (_and eventually Archive_) itself in the `Twt` struct itself. The idea comes from the following two comments [here](https://github.com/jointwt/twtxt/pull/168#issuecomment-687830872) and [here](https://github.com/jointwt/twtxt/pull/168#issuecomment-687901915) (_for other reasons_), but this gives us a nice balance of a) "no we **will not** store statistical data like this in a database that can be abused, queries or used for other nefarious prepossess and b) still gives users the added value of "affirmation" and "engagement" without "littering" the original Twt with a stream of "👍" Twts or such...

Thoughts?

**Comment by joshkitt** [comment]
I know we're waiting for collaborators to weigh in, but from my perspective, I think it sounds great. I'm interested in running my own Pod, and I think this would be awesome. I'm not familiar yet with the tech stack, and I don't know much about bitcask, but I would want to scale to hundreds of thousands of users, if that's possible. At that scale, I think it would be nice to have reactions. If you can find a way to allow reactions (and maybe even custom reactions, defined by the Pod), it would be appreciated.

**Comment by prologic** [comment]
Hmmm 🤔 When you say hundreds of thousands of users, do you mean active posters? We _haven't to date_ design the backend software to scale like this, rather the opposite, decentralised network of interconnected pods.

**Comment by prologic** [comment]
Kind of curious too what the use-case for a Pod of this size would be? Do you mind opening another issue to discuss this kind of use-scale, scalability and the issues therein (_if any_)?

**Comment by felixplesoianu** [comment]
I like that twtxt(.net) doesn't bother with likes and retweets. Mastodon blithely copied Twitter's design, including these two misfeatures, and with them much of the toxicity it hoped to leave out.

We don't need artificial engagement. That's for social media giants who spy on people for the benefit of advertisers. If you're feeling engaged, leave a reply. Even just with emoji in it, if you're not feeling wordy at the time.

**Comment by prologic** [comment]
@felixplesoianu's comment is _precisely_ the same sentiment I feel about this too and have always stood by this from the very beginning of the design from first launch date. There is _nothing_ stopping you from replying to a Twt or Twt Blog with a single "👍" if that's what you feel inclined to do -- even if we _feel_ that this _might_ clutter up the "Conversation" or "Comments" (_if a Twt Blog_), that's "okay" because the archiver will kick in at some point and start arching them away anyway.

I've had _many_ an argument with my old man over this very topic of "do we" or "don't we" add this kind of feature. I've maintained we do not for the same stated reasons as @felixplesoianu . I _feel_ it devalues the conversations and adds a level of "social anxiety" (_think of the types of people that anxiously away their next 👍 🤣 ❤️ etc_)

I'm not convinced by the argument of "affirmation" or "engagement" really, the arguments for this would have to be made much stronger IHMO, and as I stated above we _would absolutely never_ do it in such a way as to make it easier to abuse statistically / numerically.

**Comment by lwojcik** [comment]
Ooookay, I felt this issue would eventually arise sooner or later.

Let me preface this by saying I share the negative sentiment about social media reactions in general. I'm okay with Twtxt.net not supporting them as they would contribute nothing of value to my life. It took me some time to cut the connection between my general happiness and the amount of times people clicked some heart icon next to silly content I post online and it felt great. I'm generally very picky about signals I want to receive online.

But I'm not convinced if ruling reactions out completely for other people is a sensible idea. At least not for the reasons I've read in the comments above. And I feel like playing a devil's advocate even if the case is lost, because I find it boring to always agree with everyone on everything.

I still use Twitter on a daily basis to talk to a small circle of people I'd had never met anywhere online otherwise. I treat reactions like a multitool to quickly deliver different kinds of messages. Sometimes the message is just 'thanks for sharing', sometimes it just means 'mark this tweet as read', sometimes the message is 'I don't agree with this, but it sounds reasonable and I appreciate you tweeted that'. I can't possibly know if I'm funding a dopamine shot to another social media addict or just giving something the other person would interpret as a friendly nudge. Plus it's none of my business.

Being on the receiving side Twitter likes are often the only interaction I'll get from my some people who follow me. We don't always have enough common ground to talk. Maybe they can't formulate their reply in English due to poor language skills. Maybe I'm just another funny source of random noise in their feeds and they don't feel like talking to me at all. By disregarding this feature we effectively silence quite a significant group of people.

Some time ago at work we had an online conference with a board member running our department, including a multi-hour QA session. The session was heavily moderated, but numerous questions were asked, some of them quite uncomfortable. And those exact questions were given dozens of thumb-ups, effectively sending a message to the powerful guy on the other side of our screens that this is exactly what is bothering us. Very simple thing that spoke louder than anything.

> There is nothing stopping you from replying to a Twt or Twt Blog with a single "+1" if that's what you feel inclined to do -- even if we feel that this might clutter up the "Conversation" or "Comments" (if a Twt Blog), that's "okay" because the archiver will kick in at some point and start arching them away anyway.

In all seriousness I really hope this practice of posting +1 doesn't become a daily reality in Twtxt. Even if the archiver does its job sooner or later, it won't pay back all those small debts it took from my attention budget every time I scroll through a bunch of +1s / thumb-ups in a row. Likes on Twitter effectively filter out this type of interactions leaving more space for more well-thought replies.

>  I feel it devalues the conversations and adds a level of "social anxiety" (think of the types of people that anxiously away their next +1 rofl heart etc)

We have this exact feature on GitHub and I can see it being used all the time. What if the other commenter here is that exact type of person? What if I told you the next thing once I post this comment I'd refresh the page a dozens of times to see if anyone reacted to it (actually I'm not going to do that but do you believe me just because I told you so)? What exactly makes Facebook / Twitter likes worse than reactions on GitHub? How can we blame social media reactions for anything that's wrong about the discourse online while we see no problem using their incarnation here? Aren't we actually a part of the problem that way? Isn't this a bit hypocritical?

Anyway, my general take on this is the following:

1. I don't perceive reactions as a high priority feature on Twtxt, I can live without them just as fine as anywhere on the internet,

2. If they ever get implemented, I'd love them to be configurable either by a pod operator or myself in the profile settings so that I can decide if I ever want to see and use them / change to a pod with different policy / do whatever on my own instance.

**Comment by prologic** [comment]
Thanks @lwojcik for poking holes in my own arguments! Much appreciated! Very keen to hear more opinions for and against, and as I said even if we do this we would be rather deliberate about "how". As an example of another platform that doesn't have Reactions btw, [Micro.blog](https://micro.blog) -- And yet I _almost never_ see comments with just "👍" for example. Your arguments however are quite strong **for** this feature especially the part about "silencing quite a number of people" that wouldn't otherwise have much to say except a small "reaction" or two.

**Comment by aaadonai** [comment]
Just adding to the conversation something related with the "social anxiety" and "approval seeking" yet different enough IMO to be worth mentioning.
What if with the implementation of "likes" and/or "reactions" one starts focusing on things worth paying attention to?
For example, I am now scrolling through the twt posts and only stopping to reading the ones I see people are liking the most. Is it a good or bad thing? Is it a valuable "community filtering"?
Will user do that consciously or will they not even notice they are doing it? 

I like the idea @lwojcik gave above on this been configurable by pod owner and also the users be able to turn on or off on their profile's. I would also add to that saying that likes counts shouldn't be visible to others.

**Comment by prologic** [comment]
> What if with the implementation of "likes" and/or "reactions" one starts focusing on things worth paying attention to?
> For example, I am now scrolling through the twt posts and only stopping to reading the ones I see people are liking the most. Is it a good or bad thing? Is it a valuable "community filtering"?
> Will user do that consciously or will they not even notice they are doing it?

Aside from the temptation to do numerical/statistical things with the data (_something I'd like to avoid_), this is what I worry about the most honestly. I _believe_ we as humans have an internal bias, and way back when this whole "social media" thing was invented (_by whom?_) I _believe_ this was a (_uncommon?_) known fact. That be adding simple buttons people can click on plays on human emotion. There's a lot of psychology behind some of the original design choices of traditional "social media" that have become rather problematic IHMO.

So yes, I _think_ it would bias what you view/read and respond to. Even if you do it unconsciously.

**Comment by prologic** [comment]
Just expanding on @aaadonai 's idea, what I _think_ could work without compromising too much is:

- Provide a "quick response" / "quick feedback" on Twt(s) and Twt Blog(s) (_no idea what we call them?_)
- These are shoved into the cache.
- They are only **visible** to the original author.

Does this work? If so, some questions:

- What do we call these?
- What should the UI/UX look like?
- What set of "things" do we allow as permissible?

**Comment by aaadonai** [comment]
I like it and I am interested to hear what other have to say.

**Comment by prologic** [comment]
I am closing this for now, not as an indication we won't do this or are completely against it (_see my comments above and some of the comments/reactions from the dev team here_), but that this is not our biggest priority. If/When this comes up again we'll refer to this issue as the previous discussion around this and continue from there.
