### ISSUE TITLE
RFC: Twtxt Feed Specification

### ISSUE THREAD

**Issue by prologic** [jointwt/twtxt#323]
I'd like to propose (_finally_) that in additional to the original [twtxt](https://twtxt.readthedocs.org) spec, that a full Twtxt Feed (_which will be the term used from here on_):

- **MUST** have a valid URI to a `twtxt.txt` file conforming to the [twtxt](https://twtxt.readthedocs.org) format.
- _Should_ have a `config.yaml` or `config.json` alongside the `twtxt.txt` at the same Base URL.
- _May_ have a `avatar.png` or `avatar.jpg` alongside the `twtxt.txt` at the same Base URI.

Hopefully the reasons are fairly obvious, but I'd like to discuss these here and flesh out a full spec to be added to [dev.twtxt.net](https://dev.twtxt.net).

cc @der-lyse 😉

**Comment by der-lyse** [comment]
Avatars are obvious, do you have any further information on the configs? What are they about? Does it specify nick name and a description which is displayed on twtxt.net user profiles? What else?

I can already see a potential problem: Depending on what they will be used for, maybe a more specific (default) config filename such as _twtxt.{yaml,json}_ would be better, because there might be other systems running along which may have already taken this fairly general filename.

We probably also need to come up with some mechanism to advertise the exact filenames, so that the filename probing of both configs and avatars (the source code specifies certainly more paths to be looked for) can be reduced. This helps saving bandwidth and also avoids web server access and/or error log entries for those failed attempts.

**Comment by der-lyse** [comment]
Ah, #310 provides some more insight on configs.

**Comment by dbohdan** [comment]
You should invite @buckket to this discussion.

**Comment by prologic** [comment]
> You should invite @buckket to this discussion.

I would like that 🤗

**Comment by dbohdan** [comment]
I sent a message to @buckket on #twtxt.

If you are going to generate and parse JSON, why not [JSON Feed](https://jsonfeed.org/version/1.1) instead of twtxt? :thinking:  I'm somewhat serious.  JSON Feed has standardized metadata fields.

I think any external ~config~ metadata file should be named the same as the feed file with a different extension.  E.g., if the feed is <tt>my-cool-feed.txt</tt>, the metadata should be <tt>my-cool-feed.json</tt> or <tt>my-cool-feed[.ini](https://en.wikipedia.org/wiki/INI_file)</tt> or <tt>my-cool-feed[.properties](https://en.wikipedia.org/wiki/.properties)</tt> to make possible multiple feeds with different metadata in the same directory.  You can either specify the path to the avatar in the metadata file or just name it <tt>my-cool-feed.png</tt>.

**Comment by prologic** [comment]
> I think any external ~config~ metadata file should be named the same as the feed file with a different extension.  E.g., if the feed is <tt>my-cool-feed.txt</tt>, the metadata should be <tt>my-cool-feed.json</tt> or <tt>my-cool-feed[.ini](https://en.wikipedia.org/wiki/INI_file)</tt> or <tt>my-cool-feed[.properties](https://en.wikipedia.org/wiki/.properties)</tt> to make possible multiple feeds with different metadata in the same directory.  You can either specify the path to the avatar in the metadata file or just name it <tt>my-cool-feed.png</tt>.

Actually I like this approach a lot 👌
