### ISSUE TITLE
Editing Twts can break Conversations

### ISSUE THREAD

**Issue by prologic** [jointwt/twtxt#327]
__NOTE:__ I _haven't_ tested this yet, but..

I _suspect_ based on knowledge of the codebase and observations of use that editing a Twt that already has a Conversation (_a chain of twts with matching Twt Hashes in the Subject_) breaks the conversation. i.e: You cannot load the conversation anymore or link to it. You _can however_ continue to search for Twts matching those tags via the search API.

I'm just documenting this here to discuss potential solutions, or even if we should attempt to solve this. This can be problematic as it ends up being "surprising" behavior to end users and results in a poor user experience (UX).

**Comment by der-lyse** [comment]
I experienced the same when working on my client, so you are absolutely correct. Unfortunately, I don't think there's anything we can do about it, other than changing the twt hash algorithm (or even introducing a completely new twt ID field instead (GUID generated by the client), really not backwards-compatible). Disabling to edit the twt on twtxt.net's end would still allow external feeds to update their twts. But even detecting whether a certain twt is used as an origin of a conversation is not reliably possible: The conversation may be ongoing unnoticed by twtxt.net on other servers or clients. Or a reply may have not been seen by twtxt.net yet, because of sync delays or users who are in the process of replying.

Probably the best we can do is to present a warning to the users to make them aware of this potential problem, once they want to edit a twt. If we know for sure that a conversation is going on, the warning may be even more aggressive.

The only case where we know for sure that a twt has never been read by anybody (and thus there's no chance to be used as a conversation root twt) is when we know that the feed has not been fetched by anyone so far since the twt in question was published. But I don't know twtxt.net's sync internals, so maybe this scenario isn't even possible.

**Comment by prologic** [comment]
> Probably the best we can do is to present a warning to the users to make them aware of this potential problem, once they want to edit a twt. If we know for sure that a conversation is going on, the warning may be even more aggressive.

I _think_ we can do this.

> The only case where we know for sure that a twt has never been read by anybody (and thus there's no chance to be used as a conversation root twt) is when we know that the feed has not been fetched by anyone so far since the twt in question was published. But I don't know twtxt.net's sync internals, so maybe this scenario isn't even possible.

This is hard-coded to ~5mins at the time of writing this comment. We _can_ rely on this however even if configurable. We can track the state of User's feeds and whether or not they have been fetched since last edit and if so ensure they still want to perform the edit.

OTOH Editing is _probably_ a bad idea, and conflicts with content addressing 🤣

**Comment by sorenpeter** [comment]
Could a way to keep conversations form breaking be to use the timestamp to chain the twt together and still allow editing of twts?

So when you click the reply icon, then the timestamp of that twt is put into brackets instead of the hash.
For this to work it should not be allowed to edit the timestamp of twts, but only the content, which would also help not breaking the chronology of a conversation.

I know that timestamps might not be as unique as a hash, but combined with the @mentions it would be.

Here is a demo of my idea. I hope it makes sense.

```
Peters.txt:	2021-01-19T19:03:01+00:00	Conversation starter: Ice cream or waffles?

James.txt:	2021-01-19T19:03:10+00:00	@<Peter URL> (2021-01-19T19:03:01+00:00) why not both?!

Alice.txt:	2021-01-19T19:03:15+00:00	@<James URL> (2021-01-19T19:03:10+00:00) I like JAM!!
```

It would be nice if the timestamp is not rendered to the user, but using data that is already present in any twtxt.txt, also outside this platform, it would be easier to have a conversation across pods. And you won't need a fancy UI, you can just copy the timestamp for the original source.

Of course this approach would not allow for a simple search to catch all the twts of a conversation. you would have to follow all the mentions+timestamps back in time...

**Comment by prologic** [comment]
This _could_ work, however it would:

* break all existing Twt hashes (_we've already done this once, we shouldn't do it again!_)
* It would not correctly "address" an actual Twt, the Twt Hashes currently are what we call "Content Addressing".
* It would collide far too often as you could have multiple mentions and timestamps all at the same time which would be worse :D

I _think_ the problem _could_ be solved by preserving the original Twt in the archive, even if it was deleted or slightly modified. The problem today is that Twts are only archived once they teach `--max-cache-items` or `--max-cache-ttl` (_whichever comes first_). But if we archive twts a pod fetches immediately then this problem is _likely_ resolved as the modified/deleted Twt that started a conversation would be present in a Pod's archive anyway.

The only downside to this approach is the fact that a user _might_ have deleted or edited the Twt on purpose.

The alternative is as @der-lyse suggested which is to build in some smarts at the backend whereby if _we_ know that a user's feed has been fetched, that you can no longer edit or delete your last twt. That is to say you have approximately ~5mins at least to change your mind. This _could_ work nicely too.

If it were me I'd go with the later approach.

**Comment by sorenpeter** [comment]
Isn't the whole idea with twtxt to give the user control over what they post?!
If you make it impossible to go back and edit/delete old twts by archiving them for the sake of making some "fancy features" work, then it we are kind of back to building silos.

Regarding your 3th point of feedback: The timestamp should never stand also. it should always be paired with a @mention. the combination will then be what tricker the conversation feature. But again I have no idea if this is technically sound or only conceptually...

**Comment by prologic** [comment]
No, it's not nearly as bad as you thin. Twt Subject(s) were something we noticed in general as a "convention" so we formalised it. Hashing a Twt makes perfect sense here where its becomes content addressable.

Maybe @dbohdan can chime in here since he actually designed and helped implement the Twt Hash in the first place and helped us with content addressing.

The extensions documented at https://dev.twtxt.net/ btw are something we plan to try to incorporate into other clients such as @quite 's [twet](https://github.com/quite/twet) and @mdom 's [txtnish](https://github.com/mdom/txtnish) as we feel these are both valuable and highly desirable extensions to the spec which were really born out of convention and necessity.

And btw... There are well of ~300k Twts that follow this convention and use hashes to address individual twts and form conversation chains. Just look at [@stats](https://twtxt.net/user/stats) 😀
