### ISSUE TITLE
Support for 0xff.nu Twt Subject Tabs

### ISSUE THREAD

**Issue by JonLundy** [jointwt/twtxt#371]
**Is your feature request related to a problem? Please describe.**

Within the grater community of Twtxt there are various extensions to allow for conversation. This request aims at being compatible with the subject extension crated by 0xff.nu picoblog.

Picoblog automatically appends a unique hash followed by a tab before the text of the tweet begins. This hash value can be used to create threaded replies. Unlike the implementation built into twt.social it has its own benefits such as durability with feed relocation.

**Describe the solution you'd like**

This request is to make twt.socal have compatibility with these hash values. The change would be to identify twts that begin with a hash followed by a tab to be the subject for the twt. Replies will append the hash inside subject parens.

**Comment by prologic** [comment]
If hxii implements Twt Subject(s) in PicoBlog, which I _believe_ he has done now as I can see them for example [this one](https://twtxt.net/twt/yltxwna) then we don't really need to do much here (_if at all_).

The only problem that remains to be discussed is whether or not we change how conversations work at all? Today the requirement is that it **must** be a valid Twt addressed by a Twt Hash which is found by looking for the Twt Hash in the Twt Subject(s) of fetched twts. The "Conversation" chain is formed on _any_ pod from active cache.

That is you cannot view conversations that exceed `--max-cache-items` or `--max-cache-ttl` -- This is by design.

I personally am against changing how this work for several reasons:

- It becomes harder to reason about what a "Conversation" is anymore.
- The conversation's root Twt is no longer a valid addressable Twt anywhere in the global Twtiverse space.

**Comment by JonLundy** [comment]
No longer needed. Hxii has added () around the twts
