### ISSUE TITLE
Integrating with Git

### ISSUE THREAD

**Issue by hjertnes** [jointwt/twtxt#38]
It would be great if twtxt.net also supported to expose your twtxt feed as a text file, for example by letting the user specify a Git repo and ssh key.

**Comment by prologic** [comment]
Hmmm 🤔 You can't _surely_ mean "expose"; as this is already true. The user feed endpoint (_currently_) https://twtxt.net/u/prologic is already exactly that.

On the backend it is a `twtxt.txt` file too.

So how does Git come into play here? You want to be able to "insert my public rsa key here" and "git clone", "git commit -a -m ..." and "git push" to your hosted twtxt.net feed? :)

**Comment by hjertnes** [comment]
Yes. As a way for people who prefer to manage their twtxt file as a file most of the time. But would like some of the stuff twtxt.net has some times

**Comment by prologic** [comment]
So if we do something like this:

- Add an "Advanced settings" section for User accounts
- Here you can place your public SSH RSA key.
- Expose a git://twtxt.net/<username>.git repo

This repo will contain two things:

- `twtxt.txt`
- `config.yml`

Does this work for you? It's a lot of work though...

**Comment by hjertnes** [comment]
I though about doing it the other way. That the user provide the repo that will be used

**Comment by prologic** [comment]
> I though about doing it the other way. That the user provide the repo that will be used

Ahh I see. How would the twtxt.net platform write/push to it? Or would this bs one-way / read-only from twtxt.net's perspective?

**Comment by hjertnes** [comment]
I thought both, so that you get both the "I control this file" aspect, but can still use stuff like replies from twtxt.net.

**Comment by hjertnes** [comment]
I guess twtxt would to a git pull, then write to the file, commit and push?

**Comment by hjertnes** [comment]
And I guess twtxt either could do a pull and update it's internal version of the file on a interval or require the client to do a API call when it have been updated

**Comment by eludom** [comment]
So, I've thought this through a bit.

If the goal is to a) have a twtxt.txt file at a random place (likely git-based) off-pod be the "authoritative" feed for a users b) have tweets generated on the pod show up in the authoritative twtxt.txt file automatically and c) have them show up without delay...

...then, some sort of private key (.e.g. ssh) will need to be stored on the pod so the push can happen.  That is a decision that has to be made.   Can/will/should the pod store private keys/passwords etc?

The alternatives would  seem to be the source doing some sort of pull.   This would, I think, involve some sort of scheduled job (think cron or maybe some CI/CD thing) periodically pulling from the pods local (git) repo.    Updates would not be instant and would depend on the scheduled job running.

Thoughts?

**Comment by eludom** [comment]
One possible workflow looks like this 

POD - is local git repo on pod
GITHUB - is github repo, this is the the authoritative repo, containing txtxt.txt
LAPTOP - is github repo on, e.g. y laptop.

Process:

 * POD initiated updats:
   - Pull from GITHUB (fetch, merge)
   - git add, commit local changes
   - git push to GITHUB

* LAPTOP initiated updates
  - git pull from GITHUB (fetch, merge)
  - git add, commit local changes
  - git push

**Comment by prologic** [comment]
So I _think_ having private keys on the pod side is "okay" as long as they are generated and we're not asking hte user to upload their own private ssh key.

That being said, I _think_ it would be generally better anyway if we just adopt a Pull/Sync model anyway, ala Github, whereby a User that has an account on a Pod can configure their account to say "here is there my `twtxt.txt` file is hosted, please use this Git URI".

So this means each Pod would also have an SSH server builtin?

The flow would look one thing:

- User commits new Twts to their local repo containing their `twtxt.txt` feed file.
- Pod periodically pulls from this Git repo and updates the user's feed.

And if the user logs into their Pod account via Web or Mobile and posts:

- User logs into Pod from Web/Mobile and makes a Twt or two.
- User from local Git repo pull/merges from Pod
- User makes new commits new Twts to their local Git repo
- Pod periodically pulls from this Git repo and updates the user's feed.

So this _should_ be a seamless two-way thing right?

Technically source-of-truth is on both sides really, but since a user is free to delete their account on the pod they retain their local Git repo and original `twtxt.txt` feed file.

For me there isn't really a lot of advantages to this for me per se, since I already self-host my own pod (twtxt.net) and others can too, or join one they are happy with. But this feature request came out of some users wanting some of the added features/advantages of the features we've built with the backend software and API but whilst retraining ownership/control over their `twtxt.txt` feed file.

Thoughts?

**Comment by eludom** [comment]
So the pull model would probably work.   Major downside is lag time.   If the periodic pulls are, say, every 3 hours, you can be 3 hours out of date.   A few heuristics could make this better, e.g. the minute a user becomes active on the pod, do a pull.   Before any post to the pod, do a pull (partially to avoid merge conflicts). 

I worry about git in general and merge conflicts in particular: https://imgs.xkcd.com/comics/git_2x.png

This is all starting to seem unnecessarily complex.   My fascination with twtxt came form its simplicity.
No account.  No servers (aside from wherever you place your twtxt.txt file). No company. Simple text tweets.  One line per tweet.   No gui.   No android/iPhone app with all the bloat, spyware, adware, Play store control.  No excessively long human-and-text unfriendly URLs.   Short form.  No dancing bear GIFs or huge strings of emojiis.     This is all getting lost.

My use of twtxt will be primarily command line.   My interest in twtxt.net/pods (and hence this particular issue) is to do what I can to be a gadfly to keep format changes and operational issues friendly to those of us who choose to stay text-based command-line junkies using the (original) simple txtxt model.

**Comment by prologic** [comment]
There are (_undocumented_) future plans to expand the API and command-line client `twt` to support "syncing".

**Comment by eludom** [comment]
Sounds good.   I'd be up for testing/using api versions.

Dec 26, 2020 8:07:41 PM James Mills <notifications@github.com>:
